package com.alpha.entity;
// Generated 2018/04/16 20:54:36 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CalcQuestion generated by hbm2java
 */
@Entity
@Table(name = "CALC_QUESTION")
public class CalcQuestion implements java.io.Serializable {

	private CalcQuestionId id;
	private String question;

	public CalcQuestion() {
	}

	public CalcQuestion(CalcQuestionId id) {
		this.id = id;
	}
	public CalcQuestion(CalcQuestionId id, String question) {
		this.id = id;
		this.question = question;
	}

	@EmbeddedId

	@AttributeOverrides({@AttributeOverride(name = "grade", column = @Column(name = "GRADE", nullable = false)),
			@AttributeOverride(name = "month", column = @Column(name = "MONTH", nullable = false)),
			@AttributeOverride(name = "no", column = @Column(name = "NO", nullable = false))})
	public CalcQuestionId getId() {
		return this.id;
	}

	public void setId(CalcQuestionId id) {
		this.id = id;
	}

	@Column(name = "QUESTION", length = 200)
	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

}
