package com.alpha.entity;
// Generated 2018/04/16 20:54:36 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CalcHistoryId generated by hbm2java
 */
@Embeddable
public class CalcHistoryId implements java.io.Serializable {

	private int historyno;
	private Integer num1;
	private Character opt1;
	private Integer num2;
	private Character opt2;
	private Integer num3;
	private Character opt3;
	private Integer num4;
	private Character opt4;
	private Integer num5;
	private Integer answer;
	private Integer answerPos;
	private char success;
	private Integer times;
	private String registTime;

	public CalcHistoryId() {
	}

	public CalcHistoryId(int historyno, char success) {
		this.historyno = historyno;
		this.success = success;
	}
	public CalcHistoryId(int historyno, Integer num1, Character opt1, Integer num2, Character opt2, Integer num3, Character opt3, Integer num4, Character opt4,
			Integer num5, Integer answer, Integer answerPos, char success, Integer times, String registTime) {
		this.historyno = historyno;
		this.num1 = num1;
		this.opt1 = opt1;
		this.num2 = num2;
		this.opt2 = opt2;
		this.num3 = num3;
		this.opt3 = opt3;
		this.num4 = num4;
		this.opt4 = opt4;
		this.num5 = num5;
		this.answer = answer;
		this.answerPos = answerPos;
		this.success = success;
		this.times = times;
		this.registTime = registTime;
	}

	@Column(name = "HISTORYNO", nullable = false)
	public int getHistoryno() {
		return this.historyno;
	}

	public void setHistoryno(int historyno) {
		this.historyno = historyno;
	}

	@Column(name = "NUM1")
	public Integer getNum1() {
		return this.num1;
	}

	public void setNum1(Integer num1) {
		this.num1 = num1;
	}

	@Column(name = "OPT1", length = 1)
	public Character getOpt1() {
		return this.opt1;
	}

	public void setOpt1(Character opt1) {
		this.opt1 = opt1;
	}

	@Column(name = "NUM2")
	public Integer getNum2() {
		return this.num2;
	}

	public void setNum2(Integer num2) {
		this.num2 = num2;
	}

	@Column(name = "OPT2", length = 1)
	public Character getOpt2() {
		return this.opt2;
	}

	public void setOpt2(Character opt2) {
		this.opt2 = opt2;
	}

	@Column(name = "NUM3")
	public Integer getNum3() {
		return this.num3;
	}

	public void setNum3(Integer num3) {
		this.num3 = num3;
	}

	@Column(name = "OPT3", length = 1)
	public Character getOpt3() {
		return this.opt3;
	}

	public void setOpt3(Character opt3) {
		this.opt3 = opt3;
	}

	@Column(name = "NUM4")
	public Integer getNum4() {
		return this.num4;
	}

	public void setNum4(Integer num4) {
		this.num4 = num4;
	}

	@Column(name = "OPT4", length = 1)
	public Character getOpt4() {
		return this.opt4;
	}

	public void setOpt4(Character opt4) {
		this.opt4 = opt4;
	}

	@Column(name = "NUM5")
	public Integer getNum5() {
		return this.num5;
	}

	public void setNum5(Integer num5) {
		this.num5 = num5;
	}

	@Column(name = "ANSWER")
	public Integer getAnswer() {
		return this.answer;
	}

	public void setAnswer(Integer answer) {
		this.answer = answer;
	}

	@Column(name = "ANSWER_POS")
	public Integer getAnswerPos() {
		return this.answerPos;
	}

	public void setAnswerPos(Integer answerPos) {
		this.answerPos = answerPos;
	}

	@Column(name = "SUCCESS", nullable = false, length = 1)
	public char getSuccess() {
		return this.success;
	}

	public void setSuccess(char success) {
		this.success = success;
	}

	@Column(name = "TIMES")
	public Integer getTimes() {
		return this.times;
	}

	public void setTimes(Integer times) {
		this.times = times;
	}

	@Column(name = "REGIST_TIME", length = 14)
	public String getRegistTime() {
		return this.registTime;
	}

	public void setRegistTime(String registTime) {
		this.registTime = registTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CalcHistoryId))
			return false;
		CalcHistoryId castOther = (CalcHistoryId) other;

		return (this.getHistoryno() == castOther.getHistoryno())
				&& ((this.getNum1() == castOther.getNum1()) || (this.getNum1() != null && castOther.getNum1() != null && this.getNum1().equals(castOther.getNum1())))
				&& ((this.getOpt1() == castOther.getOpt1()) || (this.getOpt1() != null && castOther.getOpt1() != null && this.getOpt1().equals(castOther.getOpt1())))
				&& ((this.getNum2() == castOther.getNum2()) || (this.getNum2() != null && castOther.getNum2() != null && this.getNum2().equals(castOther.getNum2())))
				&& ((this.getOpt2() == castOther.getOpt2()) || (this.getOpt2() != null && castOther.getOpt2() != null && this.getOpt2().equals(castOther.getOpt2())))
				&& ((this.getNum3() == castOther.getNum3()) || (this.getNum3() != null && castOther.getNum3() != null && this.getNum3().equals(castOther.getNum3())))
				&& ((this.getOpt3() == castOther.getOpt3()) || (this.getOpt3() != null && castOther.getOpt3() != null && this.getOpt3().equals(castOther.getOpt3())))
				&& ((this.getNum4() == castOther.getNum4()) || (this.getNum4() != null && castOther.getNum4() != null && this.getNum4().equals(castOther.getNum4())))
				&& ((this.getOpt4() == castOther.getOpt4()) || (this.getOpt4() != null && castOther.getOpt4() != null && this.getOpt4().equals(castOther.getOpt4())))
				&& ((this.getNum5() == castOther.getNum5()) || (this.getNum5() != null && castOther.getNum5() != null && this.getNum5().equals(castOther.getNum5())))
				&& ((this.getAnswer() == castOther.getAnswer())
						|| (this.getAnswer() != null && castOther.getAnswer() != null && this.getAnswer().equals(castOther.getAnswer())))
				&& ((this.getAnswerPos() == castOther.getAnswerPos())
						|| (this.getAnswerPos() != null && castOther.getAnswerPos() != null && this.getAnswerPos().equals(castOther.getAnswerPos())))
				&& (this.getSuccess() == castOther.getSuccess())
				&& ((this.getTimes() == castOther.getTimes())
						|| (this.getTimes() != null && castOther.getTimes() != null && this.getTimes().equals(castOther.getTimes())))
				&& ((this.getRegistTime() == castOther.getRegistTime())
						|| (this.getRegistTime() != null && castOther.getRegistTime() != null && this.getRegistTime().equals(castOther.getRegistTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getHistoryno();
		result = 37 * result + (getNum1() == null ? 0 : this.getNum1().hashCode());
		result = 37 * result + (getOpt1() == null ? 0 : this.getOpt1().hashCode());
		result = 37 * result + (getNum2() == null ? 0 : this.getNum2().hashCode());
		result = 37 * result + (getOpt2() == null ? 0 : this.getOpt2().hashCode());
		result = 37 * result + (getNum3() == null ? 0 : this.getNum3().hashCode());
		result = 37 * result + (getOpt3() == null ? 0 : this.getOpt3().hashCode());
		result = 37 * result + (getNum4() == null ? 0 : this.getNum4().hashCode());
		result = 37 * result + (getOpt4() == null ? 0 : this.getOpt4().hashCode());
		result = 37 * result + (getNum5() == null ? 0 : this.getNum5().hashCode());
		result = 37 * result + (getAnswer() == null ? 0 : this.getAnswer().hashCode());
		result = 37 * result + (getAnswerPos() == null ? 0 : this.getAnswerPos().hashCode());
		result = 37 * result + this.getSuccess();
		result = 37 * result + (getTimes() == null ? 0 : this.getTimes().hashCode());
		result = 37 * result + (getRegistTime() == null ? 0 : this.getRegistTime().hashCode());
		return result;
	}

}
