package com.alpha.entity;
// Generated 2018/04/16 20:54:36 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CalcHistory generated by hbm2java
 */
@Entity
@Table(name = "CALC_HISTORY")
public class CalcHistory implements java.io.Serializable {

	private CalcHistoryId id;

	public CalcHistory() {
	}

	public CalcHistory(CalcHistoryId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({@AttributeOverride(name = "historyno", column = @Column(name = "HISTORYNO", nullable = false)),
			@AttributeOverride(name = "num1", column = @Column(name = "NUM1")), @AttributeOverride(name = "opt1", column = @Column(name = "OPT1", length = 1)),
			@AttributeOverride(name = "num2", column = @Column(name = "NUM2")), @AttributeOverride(name = "opt2", column = @Column(name = "OPT2", length = 1)),
			@AttributeOverride(name = "num3", column = @Column(name = "NUM3")), @AttributeOverride(name = "opt3", column = @Column(name = "OPT3", length = 1)),
			@AttributeOverride(name = "num4", column = @Column(name = "NUM4")), @AttributeOverride(name = "opt4", column = @Column(name = "OPT4", length = 1)),
			@AttributeOverride(name = "num5", column = @Column(name = "NUM5")), @AttributeOverride(name = "answer", column = @Column(name = "ANSWER")),
			@AttributeOverride(name = "answerPos", column = @Column(name = "ANSWER_POS")),
			@AttributeOverride(name = "success", column = @Column(name = "SUCCESS", nullable = false, length = 1)),
			@AttributeOverride(name = "times", column = @Column(name = "TIMES")),
			@AttributeOverride(name = "registTime", column = @Column(name = "REGIST_TIME", length = 14))})
	public CalcHistoryId getId() {
		return this.id;
	}

	public void setId(CalcHistoryId id) {
		this.id = id;
	}

}
