package com.alpha.entity;
// Generated 2018/04/16 20:54:36 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sequence generated by hbm2java
 */
@Entity
@Table(name = "sequence")
public class Sequence implements java.io.Serializable {

	private String name;
	private int currentValue;
	private int increment;

	public Sequence() {
	}

	public Sequence(String name, int currentValue, int increment) {
		this.name = name;
		this.currentValue = currentValue;
		this.increment = increment;
	}

	@Id

	@Column(name = "name", unique = true, nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "current_value", nullable = false)
	public int getCurrentValue() {
		return this.currentValue;
	}

	public void setCurrentValue(int currentValue) {
		this.currentValue = currentValue;
	}

	@Column(name = "increment", nullable = false)
	public int getIncrement() {
		return this.increment;
	}

	public void setIncrement(int increment) {
		this.increment = increment;
	}

}
