package com.alpha.entity;
// Generated 2018/04/16 20:54:36 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Times generated by hbm2java
 */
@Entity
@Table(name = "TIMES")
public class Times implements java.io.Serializable {

	private TimesId id;

	public Times() {
	}

	public Times(TimesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false, length = 50)),
			@AttributeOverride(name = "times", column = @Column(name = "TIMES", nullable = false)),
			@AttributeOverride(name = "dayDelay", column = @Column(name = "DAY_DELAY", nullable = false))})
	public TimesId getId() {
		return this.id;
	}

	public void setId(TimesId id) {
		this.id = id;
	}

}
