package com.alpha.entity;
// Generated 2018/04/16 20:54:36 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TimesId generated by hbm2java
 */
@Embeddable
public class TimesId implements java.io.Serializable {

	private String userId;
	private int times;
	private int dayDelay;

	public TimesId() {
	}

	public TimesId(String userId, int times, int dayDelay) {
		this.userId = userId;
		this.times = times;
		this.dayDelay = dayDelay;
	}

	@Column(name = "USER_ID", nullable = false, length = 50)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "TIMES", nullable = false)
	public int getTimes() {
		return this.times;
	}

	public void setTimes(int times) {
		this.times = times;
	}

	@Column(name = "DAY_DELAY", nullable = false)
	public int getDayDelay() {
		return this.dayDelay;
	}

	public void setDayDelay(int dayDelay) {
		this.dayDelay = dayDelay;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TimesId))
			return false;
		TimesId castOther = (TimesId) other;

		return ((this.getUserId() == castOther.getUserId())
				|| (this.getUserId() != null && castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& (this.getTimes() == castOther.getTimes()) && (this.getDayDelay() == castOther.getDayDelay());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + this.getTimes();
		result = 37 * result + this.getDayDelay();
		return result;
	}

}
