package com.alpha.entity;
// Generated 2018/04/16 20:54:36 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user")
public class User implements java.io.Serializable {

	private String userId;
	private Integer pageOffset;
	private Integer dayLimit;

	public User() {
	}

	public User(String userId) {
		this.userId = userId;
	}
	public User(String userId, Integer pageOffset, Integer dayLimit) {
		this.userId = userId;
		this.pageOffset = pageOffset;
		this.dayLimit = dayLimit;
	}

	@Id

	@Column(name = "USER_ID", unique = true, nullable = false, length = 50)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "PAGE_OFFSET")
	public Integer getPageOffset() {
		return this.pageOffset;
	}

	public void setPageOffset(Integer pageOffset) {
		this.pageOffset = pageOffset;
	}

	@Column(name = "DAY_LIMIT")
	public Integer getDayLimit() {
		return this.dayLimit;
	}

	public void setDayLimit(Integer dayLimit) {
		this.dayLimit = dayLimit;
	}

}
