package com.alpha.entity;
// Generated 2018/04/16 20:54:36 by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Word generated by hbm2java
 */
@Entity
@Table(name = "word")
public class WordEntity implements java.io.Serializable {

	private WordEntityId id;
	private Character target;
	private String category;
	private String word;
	private String pronounce;
	private String vocabulary;
	private String nextTime;
	private String studyTime;
	private int times;
	private char favorite;
	private String sound;

	public WordEntity() {
	}

	public WordEntity(WordEntityId id, String word, String nextTime, String studyTime, int times, char favorite) {
		this.id = id;
		this.word = word;
		this.nextTime = nextTime;
		this.studyTime = studyTime;
		this.times = times;
		this.favorite = favorite;
	}
	public WordEntity(WordEntityId id, Character target, String category, String word, String pronounce, String vocabulary, String nextTime, String studyTime, int times,
			char favorite, String sound) {
		this.id = id;
		this.target = target;
		this.category = category;
		this.word = word;
		this.pronounce = pronounce;
		this.vocabulary = vocabulary;
		this.nextTime = nextTime;
		this.studyTime = studyTime;
		this.times = times;
		this.favorite = favorite;
		this.sound = sound;
	}

	@EmbeddedId

	@AttributeOverrides({@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", nullable = false, length = 50)),
			@AttributeOverride(name = "wordNo", column = @Column(name = "WORD_NO", nullable = false))})
	public WordEntityId getId() {
		return this.id;
	}

	public void setId(WordEntityId id) {
		this.id = id;
	}

	@Column(name = "TARGET", length = 1)
	public Character getTarget() {
		return this.target;
	}

	public void setTarget(Character target) {
		this.target = target;
	}

	@Column(name = "CATEGORY", length = 100)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "WORD", nullable = false, length = 50)
	public String getWord() {
		return this.word;
	}

	public void setWord(String word) {
		this.word = word;
	}

	@Column(name = "PRONOUNCE", length = 50)
	public String getPronounce() {
		return this.pronounce;
	}

	public void setPronounce(String pronounce) {
		this.pronounce = pronounce;
	}

	@Column(name = "VOCABULARY", length = 50)
	public String getVocabulary() {
		return this.vocabulary;
	}

	public void setVocabulary(String vocabulary) {
		this.vocabulary = vocabulary;
	}

	@Column(name = "NEXT_TIME", nullable = false, length = 8)
	public String getNextTime() {
		return this.nextTime;
	}

	public void setNextTime(String nextTime) {
		this.nextTime = nextTime;
	}

	@Column(name = "STUDY_TIME", nullable = false, length = 11)
	public String getStudyTime() {
		return this.studyTime;
	}

	public void setStudyTime(String studyTime) {
		this.studyTime = studyTime;
	}

	@Column(name = "TIMES", nullable = false)
	public int getTimes() {
		return this.times;
	}

	public void setTimes(int times) {
		this.times = times;
	}

	@Column(name = "FAVORITE", nullable = false, length = 1)
	public char getFavorite() {
		return this.favorite;
	}

	public void setFavorite(char favorite) {
		this.favorite = favorite;
	}

	@Column(name = "SOUND", length = 500)
	public String getSound() {
		return this.sound;
	}

	public void setSound(String sound) {
		this.sound = sound;
	}

}
